[package]
name = "rsx-redux"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.1"
priority-queue = "2.5.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
memmap2 = "0.9.7"
ringbuf="0.4.8"